version: '3.4'

services:
  gateway.service.api:
    image: ${DOCKER_REGISTRY-}gatewayserviceapi
    build:
      context: .
      dockerfile: Gateway.Service.Api/Dockerfile
    depends_on:
      - order.service.api
      - product.service.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
  
  order.service.api:
    image : ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: Ordre.Service.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORT=80
    ports:
      - 51898:80
  product.service.api:
    image : ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: Product.Service.Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - HTTP_PORT=80
    ports:
      - 15887:80

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'sample.rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
        - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
        - rabbitmq_sample_net

networks:
  rabbitmq_sample_net:
    driver: bridge

